# Generated by Django 3.0 on 2022-05-30 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220529_1415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
