# Generated by Django 3.0 on 2022-05-21 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0005_auto_20220521_0406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
