# Generated by Django 3.0 on 2022-07-02 19:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
