# Generated by Django 3.0 on 2022-07-02 22:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_book_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
    ]
