# Generated by Django 3.0 on 2022-07-02 23:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220702_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=300),
        ),
    ]
